# This is a basic workflow to help you get started with Actions
name: Build and deploy Vue 3 App to surge
# Controls when the action will run. 
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      # Install surge
      - name: Install surge
        run: npm install -g surge

      # Build using yarn
      - name: Build the App
        run: |
          yarn
          yarn build
          
      - name: Deploy
        run: |
          cd ./dist/
          surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}